before_script:
 - apt-get update --yes
 - apt-get install --yes wget gnupg gnupg2 apt-transport-https
 # add intel-mkl repository
 - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
 - apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
 - sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
 - apt-get update --yes
 - apt-get install --yes cmake build-essential libboost-all-dev intel-mkl-2019.3-062
 - source /opt/intel/mkl/bin/mklvars.sh intel64

build:
  tags:
    - hilbert
  script:
    - mkdir -p build
    - cd build
    - export CXX=g++
    - export CC=gcc
    - cmake ..
    - make -j
